### ISSUE TITLE
network-top fails

### ISSUE THREAD

**Issue by rusprapor** [strizhechenko/netutils-linux#109]
Under CentOS6

- [ ] numa.py should be aware of lscpu output without NUMA node at all.

```
[root@test ~]# network-top
Traceback (most recent call last):
  File "/usr/bin/network-top", line 7, in <module>
    NetworkTop().run()
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/network_top.py", line 24, in __init__
    self.parse_options()
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/network_top.py", line 117, in parse_options
    top.post_optparse()
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/link_rate.py", line 152, in post_optparse
    self.numa = Numa(self.options.devices, self.options.random)
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/numa.py", line 34, in __init__
    self.detect_layouts()
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/numa.py", line 77, in detect_layouts
    layouts = [list(map(int, row.split(b',')[2:4])) for row in rows]
ValueError: invalid literal for int() with base 10: ''

[root@SN4A-4M ~]# python --version
Python 2.6.6

[root@test ~]# uname -a
Linux SN4A-4M 2.6.32-504.el6.i686 #1 SMP Wed Oct 15 03:02:07 UTC 2014 i686 i686 i386 GNU/Linux

[root@test ~]# pip show netutils-linux
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Name: netutils-linux
Version: 2.0.10
Summary: Bunch of utils to simplify linux network troubleshooting and performance tuning.
Home-page: https://github.com/strizhechenko/netutils-linux
Author: Oleg Strizhechenko
Author-email: oleg.strizhechenko@gmail.com
License: MIT
Location: /usr/lib/python2.6/site-packages
Requires: prettytable, ipaddress, pyyaml, six, colorama

[root@test ~]# cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m

[root@test ~]# lscpu
Architecture:          i686
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    3
Socket(s):             2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 23
Stepping:              10
CPU MHz:               1999.788
BogoMIPS:              3999.42
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              6144K

[root@test ~]# lscpu -p
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node,,L1d,L1i,L2
0,0,0,,,0,0,0
1,1,1,,,1,1,1
2,2,0,,,2,2,2
3,3,1,,,3,3,3
4,4,0,,,4,4,2
5,5,1,,,5,5,3
```

Also fails server-info-show
```
[root@test ~]# server-info-show
Traceback (most recent call last):
  File "/usr/bin/server-info-show", line 18, in <module>
    main()
  File "/usr/bin/server-info-show", line 14, in main
    print_(Reader(datadir))
  File "/usr/lib/python2.6/site-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/lib/python2.6/site-packages/netutils_linux_hardware/reader.py", line 28, in gather_info
    "info": YAMLLike().parse_file_safe(self.path('lscpu_info')),
  File "/usr/lib/python2.6/site-packages/netutils_linux_hardware/reader.py", line 22, in path
    return os.path.join(self.datadir, filename)
  File "/usr/lib/python2.6/posixpath.py", line 67, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

While "server-info show" works.
```

**Comment by strizhechenko** [comment]
`server-info-show` working currently working only via wrapper `server-info show`.

I understood the source of the bug with network-top, it's because no NUMA node shown in `lscpu -p` output. I'll hack it in next few hours, thanks for report! :)

**Comment by strizhechenko** [comment]
It should work now, sorry for long fix :)
