### ISSUE TITLE
server-info failed to run

### ISSUE THREAD

**Issue by jurka** [strizhechenko/netutils-linux#168]
`server-info` failed to run due to python error

```
> python --version
Python 2.7.12


> pip show netutils-linux
---
Metadata-Version: 2.0
Name: netutils-linux
Version: 2.5.0
Summary: Bunch of utils to simplify linux network troubleshooting and performance tuning.
Home-page: https://github.com/strizhechenko/netutils-linux
Author: Oleg Strizhechenko
Author-email: oleg.strizhechenko@gmail.com
Installer: pip
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: ipaddress, six, pyyaml, prettytable, argparse, colorama
Classifiers:
  Development Status :: 3 - Alpha
  Intended Audience :: Developers
  Operating System :: MacOS
  Operating System :: POSIX
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.6
  Topic :: Software Development
  Topic :: Utilities

> cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

>uname -a
Linux lasvegas-nv-datacenter.serverpoint.com 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

>lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
Stepping:              7
CPU MHz:               2000.078
BogoMIPS:              4000.15
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0,1
Flags:                 fpu de tsc msr pae cx8 apic sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm epb xsaveopt dtherm ida arat pln pts

>lscpu -p
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node,,L1d,L1i,L2,L3
0,0,0,0,,0,0,0,0
1,0,0,0,,0,0,0,0
```

This is python traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/server-info-rate", line 20, in <module>
    print_(Assessor(Reader(get_datadir()).info))
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/reader.py", line 32, in gather_info
    "disk": DiskInfo().parse(self.path('disks_types'), self.path('lsblk_sizes'), self.path('lsblk_models')),
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/parsers.py", line 71, in parse
    "size": self.DiskSizeInfo(types_data).parse_file_safe(sizes),
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/parsers.py", line 20, in parse_file_safe
    return self.parse_file(filepath, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/parsers.py", line 16, in parse_file
    return self.parse(file_for_parse.read().strip(), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/parsers.py", line 94, in parse
    return dict((k, int(v)) for v, k in data)
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/parsers.py", line 94, in <genexpr>
    return dict((k, int(v)) for v, k in data)
ValueError: too many values to unpack
```

**Comment by strizhechenko** [comment]
Thank you for the report! Can you please add the following commands output?

```
LANG= lsblk -d --output=NAME,MODEL
LANG= lsblk -nlb --output SIZE,MOUNTPOINT,NAME
```

**Comment by jurka** [comment]
```
>LANG= lsblk -d --output=NAME,MODEL
NAME MODEL
xvda
xvdb

>LANG= lsblk -nlb --output SIZE,MOUNTPOINT,NAME
32212254720 /          xvda
  134217728 [SWAP]     xvdb
```

**Comment by strizhechenko** [comment]
Thank you! I'll try to reproduce and fix it this evening.

**Comment by strizhechenko** [comment]
Can you run `pip install --upgrade netutils-linux` to install 2.5.1 version and check if it works well now, please?

**Comment by jurka** [comment]
now it works, thanks
