### ISSUE TITLE
openvz, can't run server-info

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#189]
```
[root@centos-user ~]# server-info --show
cat: /proc/interrupts: Нет такого файла или каталога
Traceback (most recent call last):
  File "/usr/bin/server-info", line 8, in <module>
    ServerInfo()
  File "/usr/lib/python2.6/site-packages/netutils_linux_hardware/cli.py", line 20, in __init__
    self.main()
  File "/usr/lib/python2.6/site-packages/netutils_linux_hardware/cli.py", line 57, in main
    reader = Reader(directory)
  File "/usr/lib/python2.6/site-packages/netutils_linux_hardware/reader.py", line 17, in __init__
    self.gather_info()
  File "/usr/lib/python2.6/site-packages/netutils_linux_hardware/reader.py", line 40, in gather_info
    if self.info.get('cpu', {}).get('info', {}).get(key):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by strizhechenko** [comment]
It may be unnecessory to keep interrupts file in vz, it may be better be optional

**Comment by strizhechenko** [comment]
- no /proc/interrupts
- lscpu fails
- lspci fails
- lsblk's output is empty
- dmidecode requires /dev/mem
