### ISSUE TITLE
rss-ladder don't work on stand without NUMA nodes

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#202]
```
[root@reductor-stand statistic]# rss-ladder eth1 --cpus 0
- distribute interrupts of eth1 (-rx-) on socket None
Traceback (most recent call last):
  File "/usr/bin/rss-ladder", line 8, in <module>
    RSSLadder()
  File "/usr/lib/python2.6/site-packages/netutils_linux_tuning/rss_ladder.py", line 35, in __init__
    self.eval()
  File "/usr/lib/python2.6/site-packages/netutils_linux_tuning/rss_ladder.py", line 55, in eval
    self.apply(self.__eval(postfix, interrupts))
  File "/usr/lib/python2.6/site-packages/netutils_linux_tuning/rss_ladder.py", line 67, in apply
    print_(self.color.wrap(warning, Color.YELLOW))
AttributeError: 'NoneType' object has no attribute 'wrap'
```

**Comment by anton-cheloshkin** [comment]
у меня та же проблемка. Без NUMA nodes

rss-ladder eth1 1 --no-color
- distribute interrupts of eth1 (-rx-) on socket 1
Traceback (most recent call last):
  File "/usr/local/bin/rss-ladder", line 8, in <module>
    RSSLadder()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_tuning/rss_ladder.py", line 35, in __init__
    self.eval()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_tuning/rss_ladder.py", line 56, in eval
    self.apply(self.__eval(queue_pattern, interrupts))
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_tuning/rss_ladder.py", line 63, in apply
    affinity = list(decision)
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_tuning/rss_ladder.py", line 105, in __eval
    yield any2int(line.split()[0]), queue_name[0], rss_cpus.pop()
IndexError: pop from empty list

**Comment by strizhechenko** [comment]
А зачем параметр 1 указываете, если NUMA нет?

К слову, пришлите вывод команд:

```
python --version
pip show netutils-linux
cat /etc/issue
uname -a
lscpu
lscpu -p
```

**Comment by anton-cheloshkin** [comment]
Вот.


```
usr@host:~# python --version
Python 2.7.3

usr@host:~# pip show netutils-linux
Usage: pip COMMAND [OPTIONS]

pip: error: No command by the name pip show
  (maybe you meant "pip install show")

usr@host:~# cat /etc/issue
Ubuntu 12.04.5 LTS \n \l


usr@host:~# uname -a
Linux trkrs-proxy 3.2.0-126-generic-pae #169-Ubuntu SMP Fri Mar 31 14:43:09 UTC 2017 i686 i686 i386 GNU/Linux

usr@host:~# lscpu
Архитектура:i686
CPU op-mode(s):        32-bit, 64-bit
Порядок байтов:Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Потоков на ядро:2
Ядер на сокет:4
Сокет(ы):        1
Vendor ID:             GenuineIntel
Семейство CPU:6
Модель:          30
Stepping:              5
CPU МГц:            2528.000
BogoMIPS:              5066.35
Виртуализация:VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K

usr@host:~# lscpu -p
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node,,L1d,L1i,L2,L3
0,0,0,,,0,0,0,0
1,1,0,,,1,1,1,0
2,2,0,,,2,2,2,0
3,3,0,,,3,3,3,0
4,0,0,,,0,0,0,0
5,1,0,,,1,1,1,0
6,2,0,,,2,2,2,0
7,3,0,,,3,3,3,0

```

**Comment by strizhechenko** [comment]
У вас однопроцессорная система, вы пытаетесь переопределить автоматический выбор подходящего процессора и использовать ядра второго процессора параметром: rss-ladder eth1 **1**.

Запускайте просто и всё будет в порядке:

``` shell
rss-ladder eth1
```
