### ISSUE TITLE
server-info error

### ISSUE THREAD

**Issue by nagdevops2** [strizhechenko/netutils-linux#224]
Здравствуйте. Ошибка появляется при запуске server-info

python  3.8.10

Name: netutils-linux
Version: 2.7.11
Summary: Bunch of utils to simplify linux network troubleshooting and performance tuning.
Home-page: https://github.com/strizhechenko/netutils-linux
Author: Oleg Strizhechenko
Author-email: oleg.strizhechenko@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: pyyaml, ipaddress, argparse, colorama, six, prettytable
Required-by:

pip install --upgrade netutils-linux
Requirement already up-to-date: netutils-linux in /usr/local/lib/python3.8/dist-packages (2.7.11)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.8/dist-packages (from netutils-linux) (5.4.1)
Requirement already satisfied, skipping upgrade: ipaddress in /usr/local/lib/python3.8/dist-packages (from netutils-linux) (1.0.23)
Requirement already satisfied, skipping upgrade: argparse in /usr/local/lib/python3.8/dist-packages (from netutils-linux) (1.4.0)
Requirement already satisfied, skipping upgrade: colorama in /usr/local/lib/python3.8/dist-packages (from netutils-linux) (0.4.4)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.8/dist-packages (from netutils-linux) (1.16.0)
Requirement already satisfied, skipping upgrade: prettytable in /usr/local/lib/python3.8/dist-packages (from netutils-linux) (2.2.1)
Requirement already satisfied, skipping upgrade: wcwidth in /usr/local/lib/python3.8/dist-packages (from prettytable->netutils-linux) (0.2.5)

cat /etc/issue: Ubuntu 20.04.3 LTS

uname -a : Linux p2-h4844 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lscpu: 
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          40
On-line CPU(s) list:             0-39
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           62
Model name:                      Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Stepping:                        4
CPU MHz:                         3427.627
CPU max MHz:                     3600,0000
CPU min MHz:                     1200,0000
BogoMIPS:                        5586.51
Virtualization:                  VT-x
L1d cache:                       640 KiB
L1i cache:                       640 KiB
L2 cache:                        5 MiB
L3 cache:                        50 MiB
NUMA node0 CPU(s):               0-9,20-29
NUMA node1 CPU(s):               10-19,30-39
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon peb
                                 s bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadl
                                 ine_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat 
                                 pln pts md_clear flush_l1d

lscpu -p

CPU,Core,Socket,Node,,L1d,L1i,L2,L3
0,0,0,0,,0,0,0,0
1,1,0,0,,1,1,1,0
2,2,0,0,,2,2,2,0
3,3,0,0,,3,3,3,0
4,4,0,0,,4,4,4,0
5,5,0,0,,5,5,5,0
6,6,0,0,,6,6,6,0
7,7,0,0,,7,7,7,0
8,8,0,0,,8,8,8,0
9,9,0,0,,9,9,9,0
10,10,1,1,,10,10,10,1
11,11,1,1,,11,11,11,1
12,12,1,1,,12,12,12,1
13,13,1,1,,13,13,13,1
14,14,1,1,,14,14,14,1
15,15,1,1,,15,15,15,1
16,16,1,1,,16,16,16,1
17,17,1,1,,17,17,17,1
18,18,1,1,,18,18,18,1
19,19,1,1,,19,19,19,1
20,0,0,0,,0,0,0,0
21,1,0,0,,1,1,1,0
22,2,0,0,,2,2,2,0
23,3,0,0,,3,3,3,0
24,4,0,0,,4,4,4,0
25,5,0,0,,5,5,5,0
26,6,0,0,,6,6,6,0
27,7,0,0,,7,7,7,0
28,8,0,0,,8,8,8,0
29,9,0,0,,9,9,9,0
30,10,1,1,,10,10,10,1
31,11,1,1,,11,11,11,1
32,12,1,1,,12,12,12,1
33,13,1,1,,13,13,13,1
34,14,1,1,,14,14,14,1
35,15,1,1,,15,15,15,1
36,16,1,1,,16,16,16,1
37,17,1,1,,17,17,17,1
38,18,1,1,,18,18,18,1
39,19,1,1,,19,19,19,1

server-info --show
/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/parser.py:28: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(text)
Traceback (most recent call last):
  File "/usr/local/bin/server-info", line 8, in <module>
    Server().main()
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/server.py", line 122, in main
    print_(dict2yaml(self.read()))
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/server.py", line 60, in read
    info[key] = subsystem(datadir=self.directory).parse()
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/cpu.py", line 28, in parse
    'info': self.read(YAMLLike, 'lscpu_info'),
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/subsystem.py", line 42, in read
    return func(self.path(filename)).result
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/parser.py", line 11, in __init__
    self.result = self.parse_file_safe(filepath) if filepath else None
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/parser.py", line 22, in parse_file_safe
    return self.parse_file(filepath, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/parser.py", line 18, in parse_file
    return self.parse(file_for_parse.read().strip(), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netutils_linux_hardware/parser.py", line 28, in parse
    return yaml.load(text)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 27, column 37:
    Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages

[server.tar.gz](https://github.com/strizhechenko/netutils-linux/files/7320268/server.tar.gz)

**Comment by rayrapetyan** [comment]
Should be fixed by: https://github.com/strizhechenko/netutils-linux/pull/228
