### ISSUE TITLE
Rework option parsing

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#39]
Before #36:

1. No more environment variables.
2. https://github.com/strizhechenko/optparse-modular-example based parsing.

shortopt | longopt | owners | default | help
 --- | --- | --- | --- | ---
-i | --interval | basetop | 1 | interval between screen renew in seconds
-n | --iterations-limit | basetop | 60 or -1 | count of screen's renews, -1 - infinite loop
-- | --no-delta-mode | basetop | False | shows  metrics' values instead of growth
-- | --delta-small-hide | basetop | True | hides lines with only small changes or without changes at all
-l | --delta-small-hide-limit | basetop | True | hides lines with only changes less than this limit
-c | --(no-)color | basetop | True | highlight NUMA nodes or sockets
--assert | --assert-mode | softnet-stat-top, link-rate | False | stops running after errors detected
-- | --interrupt-file | irqtop | /proc/interrupt | option for testing on MacOS purpose
-- | --softirqs-file | softirq-net-rx-top | /proc/softirqs | option for testing on MacOS purpose
-- | --softnet-stat-file | softnet-stat-top | /proc/net/softnet_stat | option for testing on MacOS purpose
-- dev | --devices | link-rate | [] | comma-separated list of devices to monitor
--dev-regex | --devices-regex | link-rate | ^.*$ | regex-mask for devices to monitor
-s | --simple | link-rate | False | hide different kinds of error, showing only general counters
--rx | --rx-only | link-rate (and maybe softirq-net-top) | False | hide tx-counters

**Comment by strizhechenko** [comment]
Maybe devices should be args, not option.

**Comment by strizhechenko** [comment]
https://github.com/strizhechenko/netutils-linux/commit/ec4f097307b29d876052de5aee177fae034406e1

Only `network-top` util is left to fix to close this issue.

```
Traceback (most recent call last):
  File "/usr/bin/network-top", line 5, in <module>
    pkg_resources.run_script('netutils-linux==1.1.18', 'network-top')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/netutils_linux-1.1.18-py2.6.egg/EGG-INFO/scripts/network-top", line 7, in <module>
    NetworkTop().run()
  File "/usr/lib/python2.6/site-packages/netutils_linux-1.1.18-py2.6.egg/netutils_linux/network_top.py", line 20, in __init__
    self.parse_options()
  File "/usr/lib/python2.6/site-packages/netutils_linux-1.1.18-py2.6.egg/netutils_linux/network_top.py", line 50, in parse_options
    top.post_optparse()
  File "/usr/lib/python2.6/site-packages/netutils_linux-1.1.18-py2.6.egg/netutils_linux/link_rate.py", line 84, in post_optparse
    self.options.devices = self.devices_list()
  File "/usr/lib/python2.6/site-packages/netutils_linux-1.1.18-py2.6.egg/netutils_linux/link_rate.py", line 81, in devices_list
    return self.options.devices.split(',') if self.options.devices else self.devices_list_regex()
AttributeError: 'NoneType' object has no attribute 'devices'
```

**Comment by strizhechenko** [comment]
Done

``` shell
# network-top --help
Usage: network-top [options]

Options:
  -h, --help            show this help message and exit
  -i INTERVAL, --interval=INTERVAL
                        Interval between screen renew in seconds.
  -n ITERATIONS, --iterations=ITERATIONS
                        Count of screen's renews, -1 - infinite loop.
  --no-delta-mode       Shows metrics' values instead of growth.
  --no-delta-small-hide
                        Prevent lines with only small changes or without
                        changes at all from hiding.
  -l DELTA_SMALL_HIDE_LIMIT, --delta-small-hide-limit=DELTA_SMALL_HIDE_LIMIT
                        Hides lines with only changes less than this limit
  --no-color            Don't highlight NUMA nodes or sockets
  --spaces              Add spaces in numbers' representation, e.g. '1234567'
                        will be '1 234 567'
  --assert=ASSERT_MODE, --assert-mode=ASSERT_MODE
                        Stops running after errors detected.
  --dev=DEVICES, --devices=DEVICES
                        Comma-separated list of devices to monitor.
  --device-regex=DEVICE_REGEX
                        Regex-mask for devices to monitor.
  -s SIMPLE_MODE, --simple=SIMPLE_MODE
                        Hides different kinds of error, showing only general
                        counters.
  --rx, --rx-only       Hides tx-counters
  --interrupts-file=INTERRUPTS_FILE
                        Option for testing on MacOS purpose.
  --softnet-stat-file=SOFTNET_STAT_FILE
                        Option for testing on MacOS purpose.
  --softirqs-file=SOFTIRQS_FILE
                        Option for testing on MacOS purpose.
```
