### ISSUE TITLE
Bug in network-top with python 2.6

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#55]
```
Traceback (most recent call last):
  File "/usr/bin/network-top", line 7, in <module>
    NetworkTop().run()
  File "/usr/lib/python2.6/site-packages/netutils_linux/network_top.py", line 23, in __init__
    self.numa = Numa(devices=self.options.devices, fake=self.options.random)
  File "/usr/lib/python2.6/site-packages/netutils_linux/numa.py", line 20, in __init__
    self.nodes = self.FAKE if fake else self.node_cpu_dict()
  File "/usr/lib/python2.6/site-packages/netutils_linux/numa.py", line 38, in node_cpu_dict
    return dict((int(node.strip('node')), self.cpulist_read(node)) for node in self.node_list())
  File "/usr/lib/python2.6/site-packages/netutils_linux/numa.py", line 38, in <genexpr>
    return dict((int(node.strip('node')), self.cpulist_read(node)) for node in self.node_list())
  File "/usr/lib/python2.6/site-packages/netutils_linux/numa.py", line 30, in cpulist_read
    return list(self.cpulist_parse(fd.read()))
  File "/usr/lib/python2.6/site-packages/netutils_linux/numa.py", line 33, in cpulist_parse
    for _min, _max in [map(int, r.split('-')) for r in cpulist.split(',')]:
ValueError: need more than 1 value to unpack
```

**Comment by strizhechenko** [comment]
Done at 1.2.4:

https://github.com/strizhechenko/netutils-linux/commit/0c331ca353fac42b01c50cc99e7e578c49d26ff9
