### ISSUE TITLE
Bug with bonding in network-top

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#68]
http://forum.nag.ru/forum/index.php?showtopic=46335&st=980&gopid=1407303&#entry1407303

```
[root@border-area2 netutils-linux]# network-top
Traceback (most recent call last):
  File "/usr/bin/network-top", line 7, in <module>
    NetworkTop().run()
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/base_top.py", line 76, in run
    self.tick()
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/network_top.py", line 39, in tick
    self.current = self.parse()
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/network_top.py", line 30, in parse
    return dict((top_name, _top.parse()) for top_name, _top in self.tops.iteritems())
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/network_top.py", line 30, in <genexpr>
    return dict((top_name, _top.parse()) for top_name, _top in self.tops.iteritems())
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/link_rate.py", line 65, in parse
    return dict((dev, self.__parse_dev__(dev)) for dev in self.options.devices)
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/link_rate.py", line 65, in <genexpr>
    return dict((dev, self.__parse_dev__(dev)) for dev in self.options.devices)
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/link_rate.py", line 90, in __parse_dev__
    return dict((stat, self.__parse_dev_stat__(dev, stat)) for stat in self.stats)
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/link_rate.py", line 90, in <genexpr>
    return dict((stat, self.__parse_dev_stat__(dev, stat)) for stat in self.stats)
  File "/usr/lib/python2.6/site-packages/netutils_linux_monitoring/link_rate.py", line 95, in __parse_dev_stat__
    with open('/sys/class/net/{0}/statistics/{1}'.format(dev, stat.filename)) as devfile:
IOError: [Errno 20] Not a directory: '/sys/class/net/bonding_masters/statistics/rx_packets'
```

**Comment by strizhechenko** [comment]
Fixed in 1.2.21
