### ISSUE TITLE
server-info shows nothing

### ISSUE THREAD

**Issue by jazzl0ver** [strizhechenko/netutils-linux#92]
Under CentOS 7:
```
# uname -r
3.10.0-514.21.2.el7.x86_64
# server-info show
# server-info rate
#
```
Other utils do work.

----
https://github.com/strizhechenko/netutils-linux/issues/94

**Comment by strizhechenko** [comment]
May you run following commands:

```
bash -x server-info-collect server
echo $?
bash -x server-info show
echo $?
bash -x server-info rate
echo $?
```

`server-info-collect` tries to gather all data into /tmp/server/ and write /root/server.tar.gz archive, `show` and `rate` read it. I'd like to know where is fails first. Maybe some of these folders are read only?

**Comment by jazzl0ver** [comment]
```
[root@filer-1 ~]# bash -x server-info-collect server
+ set -euo pipefail
+ SYSCONFIG=/etc/sysconfig/network-scripts/
+ TMPDIR=/tmp/server
+ main server
+ prepare
+ mkdir -p /tmp/server/ethtool/g /tmp/server/ethtool/i /tmp/server/ethtool/c /tmp/server/network-scripts/
+ server_info
+ cat /proc/interrupts
+ cat /proc/meminfo
+ cat /proc/cpuinfo
+ cat /proc/scsi/scsi
+ lsblk -d --output=NAME,MODEL
+ lsblk -nlb --output SIZE,MOUNTPOINT,NAME
+ lspci
+ lscpu
+ lscpu --extended=CPU,SOCKET
+ egrep -v '[0-9]+/'
+ fgrep '' /sys/block/sda/queue/rotational /sys/block/sdb/queue/rotational /sys/block/sdc/queue/rotational /sys/block/sdd/queue/rotational /sys/block/zd0/queue/rotational
+ network_info
+ local netdev action
+ brctl show
/usr/bin/server-info-collect: line 27: brctl: command not found
[root@filer-1 ~]# echo $?
127
[root@filer-1 ~]# bash -x server-info show
+ set -euo pipefail
+ '[' show '!=' show ']'
+ server-info-collect server
[root@filer-1 ~]# echo $?
127
[root@filer-1 ~]# bash -x server-info rate
+ set -euo pipefail
+ '[' rate '!=' show ']'
+ '[' rate '!=' rate ']'
+ server-info-collect server
[root@filer-1 ~]# echo $?
130
```
After installing brctl:
```
[root@filer-1 ~]# server-info show
Traceback (most recent call last):
  File "/usr/bin/server-info-show", line 21, in <module>
    main()
  File "/usr/bin/server-info-show", line 18, in main
    print_(Reader(datadir))
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/reader.py", line 31, in gather_info
    "net": ReaderNet(self.datadir, self.path).netdevs,
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 17, in __init__
    self.net_dev_list()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 49, in net_dev_list
    self.net_dev_list_buffers()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 28, in net_dev_list_buffers
    for netdev in self.netdevs:
TypeError: 'NoneType' object is not iterable
[root@filer-1 ~]# server-info rate
Traceback (most recent call last):
  File "/usr/bin/server-info-rate", line 25, in <module>
    main()
  File "/usr/bin/server-info-rate", line 21, in main
    data = Reader(datadir).info
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/reader.py", line 31, in gather_info
    "net": ReaderNet(self.datadir, self.path).netdevs,
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 17, in __init__
    self.net_dev_list()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 49, in net_dev_list
    self.net_dev_list_buffers()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 28, in net_dev_list_buffers
    for netdev in self.netdevs:
TypeError: 'NoneType' object is not iterable
```

**Comment by strizhechenko** [comment]
Well, thank you for quick feedback, I'll try to fix it in next 2-3 days!

**Comment by sosintheass** [comment]
I've faced with the same issue on `Debian GNU/Linux 8` and `Ubuntu 16.04.2 LTS`

Here is output of commands which you provided in the [second](https://github.com/strizhechenko/netutils-linux/issues/92#issuecomment-311371144) comment

**Debian**
```
root@10 ~ # bash -x server-info-collect server
+ set -euo pipefail
+ SYSCONFIG=/etc/sysconfig/network-scripts/
+ TMPDIR=/tmp/server
+ main server
+ prepare
+ mkdir -p /tmp/server/ethtool/g /tmp/server/ethtool/i /tmp/server/ethtool/c /tmp/server/network-scripts/
+ server_info
+ cat /proc/interrupts
+ cat /proc/meminfo
+ cat /proc/cpuinfo
+ cat /proc/scsi/scsi
cat: /proc/scsi/scsi: No such file or directory
root@10 ~ # echo $?
1
root@10 ~ # bash -x server-info-collect server
+ set -euo pipefail
+ SYSCONFIG=/etc/sysconfig/network-scripts/
+ TMPDIR=/tmp/server
+ main server
+ prepare
+ mkdir -p /tmp/server/ethtool/g /tmp/server/ethtool/i /tmp/server/ethtool/c /tmp/server/network-scripts/
+ server_info
+ cat /proc/interrupts
+ cat /proc/meminfo
+ cat /proc/cpuinfo
+ cat /proc/scsi/scsi
cat: /proc/scsi/scsi: No such file or directory
root@10 ~ # echo $?
1
root@10 ~ # bash -x server-info show
+ set -euo pipefail
+ '[' show '!=' show ']'
+ server-info-collect server
root@10 ~ # echo $?
1
root@10 ~ # bash -x server-info rate
+ set -euo pipefail
+ '[' rate '!=' show ']'
+ '[' rate '!=' rate ']'
+ server-info-collect server
root@10 ~ # echo $?
1
```

**Ubuntu 16**
```
root@3 ~ # bash -x server-info-collect server
+ set -euo pipefail
+ SYSCONFIG=/etc/sysconfig/network-scripts/
+ TMPDIR=/tmp/server
+ main server
+ prepare
+ mkdir -p /tmp/server/ethtool/g /tmp/server/ethtool/i /tmp/server/ethtool/c /tmp/server/network-scripts/
+ server_info
+ cat /proc/interrupts
+ cat /proc/meminfo
+ cat /proc/cpuinfo
+ cat /proc/scsi/scsi
+ lsblk -d --output=NAME,MODEL
+ lsblk -nlb --output SIZE,MOUNTPOINT,NAME
+ lspci
+ lscpu
+ lscpu --extended=CPU,SOCKET
+ egrep -v '[0-9]+/'
+ fgrep '' /sys/block/loop0/queue/rotational /sys/block/loop1/queue/rotational /sys/block/loop2/queue/rotational /sys/block/loop3/queue/rotational /sys/block/loop4/queue/rotational /sys/block/loop5/queue/rotational /sys/block/loop6/queue/rotational /sys/block/loop7/queue/rotational /sys/block/md0/queue/rotational /sys/block/md1/queue/rotational /sys/block/sda/queue/rotational /sys/block/sdb/queue/rotational
+ network_info
+ local netdev action
+ brctl show
/usr/local/bin/server-info-collect: line 27: brctl: command not found
root@3 ~ # echo $?
127
root@3 ~ # bash -x server-info show
+ set -euo pipefail
+ '[' show '!=' show ']'
+ server-info-collect server
root@3 ~ # echo $?
127
root@3 ~ # bash -x server-info rate
+ set -euo pipefail
+ '[' rate '!=' show ']'
+ '[' rate '!=' rate ']'
+ server-info-collect server
root@3 ~ # echo $?
127
```

After installing brctl (`apt-get install bridge-utils`): 
```
root@3 ~ # bash -x server-info-collect server
+ set -euo pipefail
+ SYSCONFIG=/etc/sysconfig/network-scripts/
+ TMPDIR=/tmp/server
+ main server
+ prepare
+ mkdir -p /tmp/server/ethtool/g /tmp/server/ethtool/i /tmp/server/ethtool/c /tmp/server/network-scripts/
+ server_info
+ cat /proc/interrupts
+ cat /proc/meminfo
+ cat /proc/cpuinfo
+ cat /proc/scsi/scsi
+ lsblk -d --output=NAME,MODEL
+ lsblk -nlb --output SIZE,MOUNTPOINT,NAME
+ lspci
+ lscpu
+ lscpu --extended=CPU,SOCKET
+ egrep -v '[0-9]+/'
+ fgrep '' /sys/block/loop0/queue/rotational /sys/block/loop1/queue/rotational /sys/block/loop2/queue/rotational /sys/block/loop3/queue/rotational /sys/block/loop4/queue/rotational /sys/block/loop5/queue/rotational /sys/block/loop6/queue/rotational /sys/block/loop7/queue/rotational /sys/block/md0/queue/rotational /sys/block/md1/queue/rotational /sys/block/sda/queue/rotational /sys/block/sdb/queue/rotational
+ network_info
+ local netdev action
+ brctl show
+ MIRRORCONF_CR7=/usr/local/Reductor/userinfo/mirror_info.conf
+ MIRRORCONF_CR8_INCHROOT=/cfg/userinfo/mirror_info.conf
+ MIRRORCONF_CR8_OUTCHROOT=/app/reductor//cfg/userinfo/mirror_info.conf
+ '[' -f /usr/local/Reductor/userinfo/mirror_info.conf ']'
+ '[' -f /cfg/userinfo/mirror_info.conf ']'
+ '[' -f /app/reductor//cfg/userinfo/mirror_info.conf ']'
++ grep : /proc/net/dev
++ tr -d :
++ awk '{print $1}'
+ for netdev in '$(grep : /proc/net/dev | awk '\''{print $1}'\'' | tr -d :)'
+ ethtool -i lo
+ continue
+ for netdev in '$(grep : /proc/net/dev | awk '\''{print $1}'\'' | tr -d :)'
+ ethtool -i eth0
+ for action in i g c
+ ethtool -i eth0
+ for action in i g c
+ ethtool -g eth0
+ for action in i g c
+ ethtool -c eth0
+ '[' -f /etc/sysconfig/network-scripts//ifcfg-eth0 ']'
+ continue
+ make_archive server
+ local output=/root/server.tar.gz
+ cd /tmp/
+ tar cfz /root/server.tar.gz server
+ rm -rf /tmp/server
+ echo /root/server.tar.gz
/root/server.tar.gz
root@3 ~ # echo $?
0
root@3 ~ # bash -x server-info show
+ set -euo pipefail
+ '[' show '!=' show ']'
+ server-info-collect server
+ cd /root/
+ tar xfz server.tar.gz
+ cd /root/server/
+ server-info-show
Traceback (most recent call last):
  File "/usr/local/bin/server-info-show", line 21, in <module>
    main()
  File "/usr/local/bin/server-info-show", line 18, in main
    print_(Reader(datadir))
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/reader.py", line 31, in gather_info
    "net": ReaderNet(self.datadir, self.path).netdevs,
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/netdev.py", line 17, in __init__
    self.net_dev_list()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/netdev.py", line 49, in net_dev_list
    self.net_dev_list_buffers()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/netdev.py", line 28, in net_dev_list_buffers
    for netdev in self.netdevs:
TypeError: 'NoneType' object is not iterable
root@3 ~ # echo $?
1
root@3 ~ # bash -x server-info rate
+ set -euo pipefail
+ '[' rate '!=' show ']'
+ '[' rate '!=' rate ']'
+ server-info-collect server
+ cd /root/
+ tar xfz server.tar.gz
+ cd /root/server/
+ server-info-rate
Traceback (most recent call last):
  File "/usr/local/bin/server-info-rate", line 25, in <module>
    main()
  File "/usr/local/bin/server-info-rate", line 21, in main
    data = Reader(datadir).info
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/reader.py", line 31, in gather_info
    "net": ReaderNet(self.datadir, self.path).netdevs,
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/netdev.py", line 17, in __init__
    self.net_dev_list()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/netdev.py", line 49, in net_dev_list
    self.net_dev_list_buffers()
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_hardware/netdev.py", line 28, in net_dev_list_buffers
    for netdev in self.netdevs:
TypeError: 'NoneType' object is not iterable
root@3 ~ # echo $?
1
```

**Comment by strizhechenko** [comment]
linked issue: https://github.com/strizhechenko/netutils-linux/issues/94

**Comment by sergey-dryabzhinsky** [comment]
Same on Ubuntu 12.04:
- not installed brctl
- after install bridge-utils - same ```NoneType``` issue

**Comment by strizhechenko** [comment]
These utils were designed for my linux based DPI solution and it has specificity: all receiving traffic interfaces are working as bridge slave.

I almost got rid of `brctl` dependency and bridge logic in case of running on systems without my product, there's only test output fixing left to release bugfix.

**Comment by strizhechenko** [comment]
It was fixed in 2.0.7 build
```
pip install --upgrade netutils-linux
```
You may test it even without bridge-utils installed.
A least it works on my ubuntu 16.04.5 desktop :)

**Comment by sergey-dryabzhinsky** [comment]
Confirm. 2.0.7 works.

**Comment by strizhechenko** [comment]
@jazzl0ver is issue on centos 7 fixed too?

**Comment by strizhechenko** [comment]
I've tryed CentOS 7.3 in digitalocean and fixed all bugs I found.

Fixed: https://github.com/strizhechenko/netutils-linux/commit/3e6e2b6d1fa286014e1def5444ca167eb67b78ee

**Comment by jazzl0ver** [comment]
Yes, CentOS 7 does work now. Thanks a bunch!
