### ISSUE TITLE
server-info show error

### ISSUE THREAD

**Issue by vpashka** [strizhechenko/netutils-linux#93]
[root@pvbook ~]# server-info show
Traceback (most recent call last):
  File "/usr/bin/server-info-show", line 21, in <module>
    main()
  File "/usr/bin/server-info-show", line 18, in main
    print_(Reader(datadir))
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/reader.py", line 31, in gather_info
    "net": ReaderNet(self.datadir, self.path).netdevs,
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 17, in __init__
    self.net_dev_list()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 49, in net_dev_list
    self.net_dev_list_buffers()
  File "/usr/lib/python2.7/site-packages/netutils_linux_hardware/netdev.py", line 28, in net_dev_list_buffers
    for netdev in self.netdevs:
TypeError: 'NoneType' object is not iterable

--------------------------
ALTLinux p8

[root@pvbook ~]# uname -a
Linux pvbook.localdomain 4.9.17-un-def-alt0.M80P.1 #1 SMP PREEMPT Wed Mar 22 19:44:13 UTC 2017 x86_64 GNU/Linux

**Comment by strizhechenko** [comment]
Thank you for feedbank! It's probably because only network devices inside any bridge are currently supported (specific of product for which this util was originally developed). I'll try to fix this bug in next 2-3 days.

**Comment by vpashka** [comment]
excellent..

**Comment by strizhechenko** [comment]
linked issue: https://github.com/strizhechenko/netutils-linux/issues/94

**Comment by sergey-dryabzhinsky** [comment]
Ubuntu 16.04.2
Python 3.5
```
# server-info show
Traceback (most recent call last):
  File "/usr/local/bin/server-info-show", line 21, in <module>
    main()
  File "/usr/local/bin/server-info-show", line 18, in main
    print_(Reader(datadir))
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/reader.py", line 28, in gather_info
    "info": YAMLLike().parse_file_safe(self.path('lscpu_info')),
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/parsers.py", line 20, in parse_file_safe
    return self.parse_file(filepath, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/parsers.py", line 16, in parse_file
    return self.parse(file_for_parse.read().strip(), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/parsers.py", line 26, in parse
    return yaml.load(text)
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 2, column 15:
    CPU op-mode(s):        32-bit, 64-bit
                  ^
```

**Comment by strizhechenko** [comment]
@sergey-dryabzhinsky, thanks for feedbank! This is not the same problem as mentioned by @vpashka.
I created separate issue: https://github.com/strizhechenko/netutils-linux/issues/99

**Comment by strizhechenko** [comment]
@vpashka, it was fixed in 2.0.7 build. You may upgrade with:
```
pip install --upgrade netutils-linux
```

**Comment by vpashka** [comment]
Да! Работает...Спасибо!
Правда на моей машине, вывод полупустой, но зато без ошибок.

P.S. У меня с английским не очень хорошо, надеюсь правила github не запрещают
общение на национальном языке :)

**Comment by strizhechenko** [comment]
Как и у меня :)
И пожалуйста и спасибо еще раз за то, что сообщили о баге.
