### ISSUE TITLE
Colors import bug

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#95]
https://habrahabr.ru/post/331720/#comment_10286396

Probably colorama has some magic depending of environment.

``` python
/usr/local/bin/network-top
Traceback (most recent call last):
  File "/usr/local/bin/network-top", line 3, in <module>
    from netutils_linux_monitoring import NetworkTop
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/__init__.py", line 1, in <module>
    from netutils_linux_monitoring.irqtop import IrqTop
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/irqtop.py", line 7, in <module>
    from netutils_linux_monitoring.base_top import BaseTop
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/base_top.py", line 7, in <module>
    from netutils_linux_monitoring.colors import wrap
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/colors.py", line 7, in <module>
    2: Fore.LIGHTYELLOW_EX,
AttributeError: 'AnsiCodes' object has no attribute 'LIGHTYELLOW_EX'
```

```
Ubuntu 14.04.4 LTS
LANG=en_US.UTF-8
LANGUAGE=en_US:en
TERM=xterm
```

**Comment by sosintheass** [comment]
Same issue on debian 
```
Traceback (most recent call last):
  File "/usr/local/bin/network-top", line 3, in <module>
    from netutils_linux_monitoring import NetworkTop
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/__init__.py", line 1, in <module>
    from netutils_linux_monitoring.irqtop import IrqTop
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/irqtop.py", line 7, in <module>
    from netutils_linux_monitoring.base_top import BaseTop
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/base_top.py", line 7, in <module>
    from netutils_linux_monitoring.colors import wrap
  File "/usr/local/lib/python2.7/dist-packages/netutils_linux_monitoring/colors.py", line 7, in <module>
    2: Fore.LIGHTYELLOW_EX,
AttributeError: 'AnsiCodes' object has no attribute 'LIGHTYELLOW_EX'
```
```
Debian GNU/Linux 8
LANG=en_US.UTF-8
LANGUAGE=en_US:en
TERM=xterm-256color
```

**Comment by strizhechenko** [comment]
@sosintheass thank for feedback

Probably I should test it with my ubuntu desktop, not with ssh from macbook :)

Anyway, there's already 2.0.4 version with workaround. May you upgrade (`pip install --upgrade netutils-linux`) and tell me if everything ok now?:)

**Comment by sosintheass** [comment]
Yeah, now it's all ok, thank for the super-fast fix 👍

**Comment by RuslanLi** [comment]
Works  on Ubuntu! Great !
many thanx
