### ISSUE TITLE
Python 3.5: yaml has problems parsing lscpu output of ubuntu 16.04.

### ISSUE THREAD

**Issue by strizhechenko** [strizhechenko/netutils-linux#99]
Ubuntu 16.04.2
Python 3.5

- [x] LANG= lscpu in server-info-collect
```
# server-info show
Traceback (most recent call last):
  File "/usr/local/bin/server-info-show", line 21, in <module>
    main()
  File "/usr/local/bin/server-info-show", line 18, in main
    print_(Reader(datadir))
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/reader.py", line 28, in gather_info
    "info": YAMLLike().parse_file_safe(self.path('lscpu_info')),
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/parsers.py", line 20, in parse_file_safe
    return self.parse_file(filepath, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/parsers.py", line 16, in parse_file
    return self.parse(file_for_parse.read().strip(), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/parsers.py", line 26, in parse
    return yaml.load(text)
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 2, column 15:
    CPU op-mode(s):        32-bit, 64-bit
                  ^
```

**Comment by strizhechenko** [comment]
Didn't reproduced :(

**Comment by sergey-dryabzhinsky** [comment]
As you wish:
```
# lscpu
Архитектура:x86_64
CPU op-mode(s):        32-bit, 64-bit
Порядок байтов:Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Потоков на ядро:1
Ядер на сокет:4
Сокет(ы):        1
NUMA node(s):          1
Vendor ID:             GenuineIntel
Семейство CPU:6
Модель:          94
Model name:            Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Stepping:              3
CPU МГц:            799.941
CPU max MHz:           3900,0000
CPU min MHz:           800,0000
BogoMIPS:              7008.18
Виртуализация:VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
```

Maybe locale issues? Same with `en` locale:
```
# env LANG=en_US.UTF-8 LANGUAGE=en lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Stepping:              3
CPU MHz:               799.941
CPU max MHz:           3900,0000
CPU min MHz:           800,0000
BogoMIPS:              7008.18
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
```

**Comment by sergey-dryabzhinsky** [comment]
Without ```LANGUAGE=en``` output was in partial Russian language.

**Comment by strizhechenko** [comment]
Does `env LANG= LANGUAGE= server-info` works?

**Comment by sergey-dryabzhinsky** [comment]
Nope:
```
# env LANG= LANGUAGE= server-info
/usr/local/bin/server-info: line 5: $1: unbound variable
```

**Comment by sergey-dryabzhinsky** [comment]
```
# env LANG= LANGUAGE= server-info show
Traceback (most recent call last):
  File "/usr/local/bin/server-info-show", line 21, in <module>
    main()
  File "/usr/local/bin/server-info-show", line 18, in main
    print_(Reader(datadir))
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/reader.py", line 16, in __init__
    self.gather_info()
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/reader.py", line 31, in gather_info
    "net": ReaderNet(self.datadir, self.path).netdevs,
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/netdev.py", line 17, in __init__
    self.net_dev_list()
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/netdev.py", line 49, in net_dev_list
    self.net_dev_list_buffers()
  File "/usr/local/lib/python3.5/dist-packages/netutils_linux_hardware/netdev.py", line 28, in net_dev_list_buffers
    for netdev in self.netdevs:
TypeError: 'NoneType' object is not iterable
```

**Comment by sergey-dryabzhinsky** [comment]
Sorry. 2.0.7 works.

**Comment by strizhechenko** [comment]
So adding LANG= in gathering system information should fix it. Interesting :)
